
;Small Menu Window - Include File - DednDave, 1-2014

;###############################################################################################

WndProc PROTO :HWND,:UINT,:WPARAM,:LPARAM

;###############################################################################################

IDI_ICON      EQU 101
CID_STATUSBAR EQU 102

IDM_MAIN_MENU EQU 1000
IDM_EXIT    EQU 1101
IDM_RECOMMENDATION    EQU 1201
IDM_LISTSORT    EQU 1202
IDM_ABOUT   EQU 1301

IDM_CTXT_MENU EQU 2000
IDM_CTXT_1    EQU 2001
IDM_CTXT_2    EQU 2002

;###############################################################################################

